config/routes.rb
Rails.application.routes.draw do
  resources :posts

  #
  root 'application#splash'

  get 'api/reddit/test' => 'test#test'
  post 'api/reddit/post' => 'reddit#create'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  body       :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  title      :string(255)
#

class Post < ActiveRecord::Base
  belongs_to :user
  before_create :add_http

  private

  def add_http
    /^(?!http:\/\/)./.match(self.url) do
      self.url = "http://#{self.url}"
    end
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  token           :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  # default validations are wrong, since we aren't requiring a pw
  has_secure_password({validations: false})

  # ensure all users are created with a client-side token
  before_create do
    self.token = User.new_token
  end

  def self.find_or_create(token)
    return User.create unless token
    User.find_by_token(token) || User.create
  end

  def token!
    self.token
  end

  def to_s
    self.id.to_s
  end

  def self.find_by_credentials(cred_hash)
    User.find_by_email(cred_hash[:username])
    .try(:authenticate, cred_hash[:password])
  end


  private

  def self.new_token
    SecureRandom.hex
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session

  helper_method :current_user, :form_auth_html, :update_method_html

  # # guarantee having a user
  # before_action :current_user

  def splash

  end


  def current_user
    @current_user ||= User.find_or_create(session[:token])
    session[:token] = @current_user.token
    @current_user
  end

  def form_auth_html
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end

  def update_method_html
    "<input type='hidden' name='_method' value='patch'>".html_safe
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.last(20)
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = self.current_user
    if @post.save
      redirect_to posts_url
    else
      fail # replace with error handling later
    end
  end

  # defaults
  def show
  end

  # also defaults
  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to posts_url
    else
      fail # TODO: error handling
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end


  def post_params
    params.require(:post).permit(:title, :url, :body)
  end
end

app/controllers/reddit_controller.rb
class RedditController < ApplicationController


  def create
    url = params['url']
    title = params['title']
    subreddit = params['subreddit']
    client = RedditKit::Client.new(Figaro.env.REDDIT_USER_NAME, Figaro.env.REDDIT_PASSWORD)
    response = client.submit(title, subreddit, url: url)

    render text: response
  end


end


# client = RedditKit::Client.new(Figaro.env.REDDIT_USER_NAME, Figaro.env.REDDIT_PASSWORD)

# client.signed_in?

# client.submit('title text', 'subreddit name', url: 'http://submission url')

app/controllers/test_controller.rb
class TestController < ApplicationController


  def test
    # use HTTParty to grab the json from a sample reddit path
    # then send render that as JSON as send it to the client
    # entire point of this controller/route is for quick-and-dirty
    # JSON stuff in reddit's format for the front-end to handle

    raw_result = HTTParty.get('http://www.reddit.com/r/anonyreddit/.json')
    results = raw_result['data']['children'].map do |entry|
      entry['data'].slice('url', 'name', 'title')
    end
    render json: results
  end

  private

  def parse_post

  end


end

app/controllers/users_controlller.rb
class UsersController < ApplicationController


  def set_credentials

  end

  def sign_in

  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/application/splash.html.erb
<!-- intentionally empty -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>reduccit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>


<script>
$('#sub-nav').on('click', function (event) {
  event.preventDefault();
  Redditclone.router.navigate('#' + $('#sub-input').val(), true);
})
</script>

<%= yield %>

<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">reduccit</a>
        </div>
        <center>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">All</a>
                    </li>
                    <li><a href="#Funny">Funny</a>
                    </li>
                    <li><a href="#EarthPorn">EarthPorn</a>
                    </li>
                    <li><a href="#Sports">Sports</a>
                    </li>
                    <li><a href="#Pics">Pics</a>
                    </li>
                    <li><a href="#new">Submit your own!</a>
                    </li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" name="subreddit" placeholder="Subreddit" id="sub-input">
                    </div>
                    <button type="submit" class="btn btn-default" id="sub-nav">Navigate</button>
                    <input type="checkbox" name="over_18" value="" id="over_18">Over 18?</input>
                </form>
            </div>
        </center>
    </div>
</div>

<div id="content"></div>

</body>
</html>

app/views/posts/_form.html.erb
<h1>placeholder for posts form</h1>

<form action="<%= new_post ? posts_url : post_url(post) %>"
  method="post" accept-charset="utf-8">
  <%= form_auth_html %>
  <%= update_method_html unless new_post %>

  <label for="title">Title</label><input type="text" name="post[title]" value="<%= post.title %>" id="title">
  <label for="url">url</label><input type="text" name="post[url]" value="<%= post.url %>" id="url">


<label for="body">Body</label><textarea name="post[body]" rows="8" cols="40" id="body" value="<%= post.body %>"></textarea>


  <p><input type="submit" value="Submit Post"></p>
</form>

app/views/posts/_post.html.erb
<!-- partial for the brieft title/thumbnail/link/etc for a post -->
<a href="<%= post.url %>"><%= post.title %></a>

app/views/posts/edit.html.erb
<h1>placeholder for edit page</h1>

<%= render partial: 'form', locals: {post: @post, new_post: false} %>

app/views/posts/index.html.erb
<h1>placeholder for posts index </h1>

<%= render partial: 'post', collection: @posts %>

app/views/posts/new.html.erb
<h1>placeholder for new post</h1>

<%= render partial: 'form', locals: {post: @post, new_post: true} %>

app/views/posts/show.html.erb
<h1> placeholder for post show </h1>

<%= render partial: 'post', object: @post   %>